version: '3.8'
services:
  dev:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=webdeveloper2802
      - POSTGRES_DB=nest
  test-db:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=webdeveloper2802
      - POSTGRES_DB=nest